name: Bump Version

on:
  push:
    branches:
      - dev

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest tag and bump version
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.UI_KIT_BOT_PAT }}@github.com/${{ github.repository }}.git

          latest_tag=$(git tag -l | sort -V | tail -n 1)
          echo "Latest tag: $latest_tag"

          latest_version="${latest_tag#v}" # Remove 'v' prefix
          IFS='.' read -r major minor patch <<< "$latest_version"

          new_version="v$major.$minor.$((patch + 1))"
          echo "New version: $new_version"

          git tag "$new_version"
          git push origin "$new_version"
