name: Bump Version

on:
  push:
    branches:
      - dev

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.bump.outputs.new_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag and bump version
        id: bump
        run: |
          latest_tag=$(git tag -l | sort -V | tail -n 1)
          echo "Latest tag: $latest_tag"

          latest_version="${latest_tag#v}" # Remove 'v' prefix
          IFS='.' read -r major minor patch <<< "$latest_version"

          new_version="v$major.$minor.$((patch + 1))"
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

          git tag "$new_version"
          git push origin "$new_version"

  publish:
    needs: bump-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Set project version based on tag
        run: |
          npm version ${{ needs.bump-version.outputs.new_version }} --no-git-tag-version

      - name: Bundle build
        run: yarn rollup

      - name: Publish to npm
        run: |
          cd build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
